import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  build: {
    outDir: "dist",
    assetsDir: "assets",
    sourcemap: false,
    rollupOptions: {
      input: {
        main: "index.html",
        papers: "papers/index.html",
        works: "works/index.html",
        epilepsyEarlyWarningWork: "works/epilepsy-early-warning-system/index.html",
        cardiomegalyScreeningWork: "works/explainable-cardiomegaly-screening/index.html",
        polypSegmentationWork: "works/colonoscopy-polyp-segmentation/index.html",
        ultrasoundHeartFailureWork: "works/ultrasound-heart-failure-assessment/index.html",
        proteinMutationWork: "works/protein-mutation-and-drug-screening/index.html",
        mody2VariantWork: "works/mody2-variant-classification/index.html",
        eyeAnalysisWork: "works/fundus-and-oct-eye-analysis/index.html",
        digitalStethoscopeWork: "works/ai-digital-stethoscope/index.html",
        emgAnalysisWork: "works/neuropathy-and-myopathy-emg-analysis/index.html",
        ecoRoutingWork: "works/traffic-aware-eco-routing/index.html",
        englishAssessmentWork: "works/ai-english-exam-evaluation/index.html",
        studiumWork: "works/studium-ai-study-coach/index.html",
        cyberbullyingProtectionWork: "works/context-aware-cyberbullying-protection/index.html",
        colliderEventsWork: "works/machine-learning-for-collider-events/index.html",
        musicScoringWork: "works/ai-music-scoring/index.html",
        dartRiftWork: "works/dart-rift/index.html",
        models: "models/index.html",
        researchReasoningModel: "models/qwen3-research-reasoning-json-rl/index.html",
        experiments: "experiments/index.html",
        riskRoutedExperiment: "experiments/risk-routed-heterogeneous-kv-memory/index.html",
        foresightPaper: "papers/foresight-is-not-enough/index.html",
        nedoqwenPaper: "papers/nedoqwen/index.html",
        epilangPaper: "papers/epilang/index.html",
        myceliumPaper: "papers/mycelium/index.html",
        surprisePaper: "papers/surprise/index.html",
        personAhmet: "person/ahmet-rifat-ozturk/index.html",
        personYagiz: "person/yagiz-ekrem-dalar/index.html",
        personNedim: "person/nedim-mutlu-sezer/index.html",
        personOmer: "person/omer-faruk-aksoy/index.html",
        personArda: "person/feyzi-arda-salihoglu/index.html",
        trDocvqaPaper: "papers/tr-docvqa-synth/index.html",
        goalDriftPaper: "papers/goal-drift/index.html",
      },
    },
  },
});
